### ISSUE TITLE
Create a Matrix for diphthongs from available vowels 

### ISSUE THREAD

**Issue by brynkhaelys** [nullwaves/frickative#3]

**Comment by nullwaves** [comment]
Treated as "new" vowels created from matrix at generation time and added to the Vowel pool. 

From "Dipthong#Types" on Wikipedia:

> The non-syllabic [diacritic](https://en.wikipedia.org/wiki/Diacritic), the [inverted breve](https://en.wikipedia.org/wiki/Inverted_breve) below ⟨◌̯⟩,[[4]](https://en.wikipedia.org/wiki/Diphthong#cite_note-4) is placed under the less prominent part of a diphthong to show that it is part of a diphthong rather than a vowel in a separate syllable: [aɪ̯ aʊ̯]. When there is no contrastive vowel sequence in the language, the diacritic may be omitted. Other common indications that the two sounds are not separate vowels are a superscript, ⟨aᶦ aᶷ⟩,[[5]](https://en.wikipedia.org/wiki/Diphthong#cite_note-5) or a tie bar, ⟨a͡ɪ a͡ʊ⟩ or ⟨a͜ɪ a͜ʊ⟩.[[6]](https://en.wikipedia.org/wiki/Diphthong#cite_note-6) The tie bar can be useful when it is not clear which symbol represents the syllable nucleus, or when they have equal weight.[[7]](https://en.wikipedia.org/wiki/Diphthong#cite_note-7) Superscripts are especially used when an on- or off-glide is particularly fleeting.

In our case I would assume for now we would like to go with using a tie bar to indicate a lack of clarity at this stage. Once it's more concrete we can reimplement to support prominence. Also what is this on/off-glide nonsense.

**Comment by brynkhaelys** [comment]
https://en.wikipedia.org/wiki/Semivowel This should explain provide more info. Love this sort of question. It has to do with some of the approximates, and it's kind of out of scope of diphthongs, but it does involve them. 

Lets presume 4 different 2-syllable words /wi.a/, /wi.o/, /wu.o/, and /wu.a/. One of the most common sound changes (perhaps _the_ most common sound change) involves two vowels next to each other. "Vowel simplification" might be a broad word for it. 

In reality, you're going to say those 4 words in one of 3 ways:

make the prosodic break [.] really obvious by adding the glottal stop. 

/wi.ʔa/, /wi.ʔo/, /wu.ʔo/, and /wu.ʔa/


do away with the prosodic break entirely and just make these into diphthongs

/wia̯/, /wio̯/, /wuo̯/, and /wua̯/


or continue breaking them up into two syllables, but don't add the glottal stop. In this situation, in regular speech, the two vowels still, sort of automatically, blend together. Linguists have used the word '"glide" together'.

There are two examples below; in natural speech, I think there is no difference between the two, and I can't imagine language that _wouldn't_ do this if it didn't do the other two. 

/wi.a/, /wi.o/, /wu.o/, and /wu.a/
/wi.ja/, /wi.jo/, /wu.wo/, and /wu.wa/


This means that /j/ (the "y" sound, for clarity) and /w/ are kind of somewhere in vowel-space, but also kind of defined well in the consonant diagram. /j/ is related to those front, closed sounds, like /i/ and /ɪ/ (and even /e/). 

/w/ is related to those closed back sounds like /u/ and /ʊ/ (and even /o/). 

Notice that that "a" sounds don't have an associated glide. 

Also, to me, the distinction between like /oi̯/, /oj/, and /oʲ/ is kind of lost. Heck, in the case of /e/ I can't even make the distinction between /e/ /ei̯/, /ej/, and /eʲ/. 

Vowels:Phonology::Verbs:Grammar, in that they're both sin. There's more fuckedness to come with the /j/ sound in the future too :)

**Comment by brynkhaelys** [comment]
Tie bar is totally fine, we can go with it if you'd prefer. 

My reasoning for preferring the non-syllabic mark / ̯  / is that the tie bar looks kind of fucked in typed text; different fonts will make the tie bar appear entirely over one or the other vowel instead of in the middle where it belongs. Or its too low or too high. 

For example, on your above comment the tie bar looks both too high and too far forward, to my eyes anyway. 

That said, the tie bar is conceptually easier to understand, IMO, because it's very obvious that those two sounds are grouped together, whereas, if you didn't know any better, the non-syllabic diacritic makes it look like its one of those weird vowels like /ä/ or /o̞/. 

Your call!
