### ISSUE TITLE
Voiced/Voiceless distinction on Cluster Matrix

### ISSUE THREAD

**Issue by brynkhaelys** [nullwaves/frickative#5]

**Comment by nullwaves** [comment]
I meant to ask about this earlier. What does this mean specifically? Does this need to be matrixed or can it just be "[]Allow Voiced/Unvoiced Order Cluster, [] Allow Unvoiced/Voiced Order Cluster"?

**Comment by brynkhaelys** [comment]
I went over this verbally, but I think it's gonna be clearer written anyway, we were kind of high energy when I brought it up. 

Another really really basic, super common sound change is "cluster simplification", and, in languages with the voiced/non-voiced distinction (/p/ /b/ /t/ /d/ /k/ /g/, /s/ /z/ /sh/ /zh/ for example), one of the most common simplifications is in regard to voicing. 

Said simply, voiceless sounds don't want to get between a voiced sound and a vowel. Take two examples. 

/zka/ and /atzh/. In the first example, your vocal cords need to vibrate on the /z/, stop vibrating on the /k/, and then start vibrating on the /a/, pretty much instantly. That's a lot to do quickly, and I really don't think people ever do it. I think instead, they'd either not voice the /z/ (/ska/) or change the /k/ to voiced (/zga/). 

Same thing with the second example, /atsh/ or /adzh/ are the ways /atzh/ would be said. 

There's some English Orthography bias here, the way I choose to represent this based on how I conceive of writing. 

Like, in reality, its just that /stɑp/ and /sdɑp/ are said the exact same universally. There's no reason for me preferring these written "stop" instead of "sdop", other than that's what English orthography does. 

Unlike the thing with the vowel simplification, where I'd like that all to happen wayyy later in the procedure, I'd like this simplification to be taken care of in advance, during the sound selection step. 

So we either need to preclude these sorts of clusters (straight up not generate them), or have a box to check if you want (for some reason) to enable "un-voicing-simplified" clusters.

**Comment by nullwaves** [comment]
I think the implementation I went with is technically correct according to your explanation. We can reopen the issue if it needs tweaking. It stops any voiceless consonant occurring between a voiced consonant and a vowel.
