### ISSUE TITLE
Placement-Specific Syllable Shapes

### ISSUE THREAD

**Issue by brynkhaelys** [nullwaves/frickative#6]

**Comment by brynkhaelys** [comment]
p m u

**Comment by nullwaves** [comment]
Checkbox enable for Mora, textbox for accepted mora cosonants. Mora at the beginning of a word are never followed by a shape with no onset.

**Comment by nullwaves** [comment]
Primary
Middle
Ultimate

~~Mora, when enabled, can be a middle or ultimate syllable.~~ jk ignore that
